spring:
  application:
    name: news

  datasource:
    url: jdbc:mysql://localhost:3306/news-db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # hoặc: none, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: 127.0.0.1
    port: 6379

# Cấu hình Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: News API
    description: API documentation for News application
    version: 1.0.0
    contact:
      name: PTIT Team
      email: contact@ptit.edu.vn

# Axon Framework Configuration
axon:
  axonserver:
    enabled: false  # Disable AxonServer connection
  serializer:
    general: jackson
    events: jackson
    messages: jackson


server: 
  port: 6969
